name: Release deer
on: workflow_dispatch # could be weekly/etc or on a separate branch.

jobs:
  build-android:
    name: Build deer for Android
    runs-on: ubuntu-latest
    outputs:
      apk-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - uses: android-actions/setup-android@v3

      - uses: extractions/setup-just@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Copy example build settings
        run: |
          cp .env.example .env
          cp google-services.json.example google-services.json

      - name: Build APK
        run: just dist-build-android-gradle

      - name: Upload APK artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: android/app/build/outputs/apk/release/app-release.apk

  release:
    name: Create GitHub Release
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: android
          path: ./release/

      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1, pinned commit hash
        with:
          name: deer v${{ github.run_number }}
          tag_name: deer-v${{ github.run_number }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ./release/app-release.apk
